Date branch changes
EMURP/SSMT-UI pull request #26
Opened 2020-06-10 15:39 UTC by nikunjdoshi67

In this PR

For Date :- 

Fixed:

Date related issues, worked on edge cases where we were not able to render

Modified:

DisplayClusterData, Dashboard Table and Project Filter form for date 

For changes in UI:

Fixed:

Dashboard page by removing the static cards related to total project, node and pods

Modified:

Storybooks, routes

Removed:

Unwanted file related to the Openstack, trial files used for self testing

2020-06-10 15:57 UTC, gagansk commented
Fix the CI failures.

2020-06-10 18:35 UTC, gagansk requested changes
Why are we still using the postman api?

2020-06-10 18:35 UTC, gagansk commented on src/app/Fetchdata/DisplayClusterData.tsx
> +      api: 'https://c507295a-b340-4a31-a144-749e6fb4c08a.mock.pstmn.io/list_projects/',
Is this a call to the postman? If so, why are we still making calls to the postman?

2020-06-10 18:35 UTC, gagansk commented on src/app/Fetchdata/fetchdata.tsx
>      const url = "https://c507295a-b340-4a31-a144-749e6fb4c08a.mock.pstmn.io/list_projects";
Is this for postman?

2020-06-10 18:43 UTC, shakyav commented on src/app/Fetchdata/fetchdata.tsx
>      const url = "https://c507295a-b340-4a31-a144-749e6fb4c08a.mock.pstmn.io/list_projects";
@gagansk 
fetchdata.tsx  and fetchfilterdata.tsx files are not being used currently used, there were issues with search button when using this file so we are not using it as of now. It is kept their just for reference. We can remove it from master branch and only keep it in our local repos and only keep the displayclusterdata.tsx
@nikunjdoshi67  can update the api link to be the link provided by Sai in displayclusterdata.tsx

2020-06-11 18:40 UTC, nikunjdoshi67 commented on src/app/Fetchdata/fetchdata.tsx
>      const url = "https://c507295a-b340-4a31-a144-749e6fb4c08a.mock.pstmn.io/list_projects";
@gagansk I have resolved the merge conflicts with @shakyav

2020-06-11 19:30 UTC, shakyav commented on src/app/Fetchdata/fetchdata.tsx
>      const url = "https://c507295a-b340-4a31-a144-749e6fb4c08a.mock.pstmn.io/list_projects";
@gagansk  postman requests are over so you might not be able to see the data, working on to create another server

2020-06-11 19:34 UTC, gagansk commented on src/app/Fetchdata/fetchdata.tsx
>      const url = "https://c507295a-b340-4a31-a144-749e6fb4c08a.mock.pstmn.io/list_projects";
@shakyav Yes. I got this message 
**Failed to load resource: the server responded with a status of 429 (Too Many Requests)**
Let us discuss moving to the paid Postman service.

2020-06-11 19:38 UTC, gagansk commented
The default date is not coming up. Also, there is an unresponsive calendar in the date selection option. You can take it out.

<img width="398" alt="Screen Shot 2020-06-11 at 3 32 23 PM" src="https://user-images.githubusercontent.com/47332731/84431555-78cb0980-abf9-11ea-9230-d39a18e2e63f.png">

2020-06-15 19:32 UTC, shakyav commented
@gagansk 
this PR is also working with backend
![image](https://user-images.githubusercontent.com/53958649/84697979-0d48ab00-af1d-11ea-8c8f-0a589d733448.png)

On date selection, time duration is 7 hrs 
![image](https://user-images.githubusercontent.com/53958649/84698142-4d0f9280-af1d-11ea-87dc-372408d9ca88.png)

![image](https://user-images.githubusercontent.com/53958649/84698178-5993eb00-af1d-11ea-908b-1f7ef067e335.png)

2020-06-16 20:08 UTC, gagansk commented
LGTM

2020-06-16 20:08 UTC, gagansk approved these changes

2020-06-16 20:08 UTC, merged