Critical issues in UI resolved
EMURP/SSMT-UI pull request #82
Opened 2020-11-25 14:11 UTC by skanthed

This close #81

2020-11-25 19:51 UTC, gagansk requested changes

2020-11-25 19:51 UTC, gagansk commented on src/app/LoginPage/LoginPageForm.tsx
> +                <a href="#" onClick={onResetButtonClick} style={{ paddingLeft: "35%" }}>Reset Password</a>
Why is this being handled in PR #80 as well?

2020-11-25 19:51 UTC, gagansk commented on src/app/LoginPage/ResetPasswordForm.tsx
> +                <a href="#" onClick={onResetButtonClick} style={{ paddingLeft: "40%" }}>Login</a>
Why is this being handled in PR #80 as well?

2020-11-26 17:42 UTC, skanthed commented
As I checked out that branch from this one. I am really sorry. I am closing this pull request and again creating one more with this specific commit.

@gagansk

2020-11-26 17:42 UTC, closed without merging